### ISSUE TITLE
How it works with laravel ?!

### ISSUE THREAD

**Issue by welcoMattic** [zimt28/laravel-jquery-file-upload#1]
Hi !

I just install the bundle. But,  I'm lost !
How it works with laravel ? There's no docs on bundle page, or here.

Can you give me some help, it looks like very nice bundle !

**Comment by zimt28** [comment]
Hey!
Well, after installing it should already work with Laravel.
As the bundle uses the blueimp file upload you can use these docs: https://github.com/blueimp/jQuery-File-Upload/wiki

The main question is what you want to do with this bundle, maybe I can help you then :)

**Comment by welcoMattic** [comment]
Hi !

I've already seen these docs.

To be clear, i want ti use this plugin for my blog admin interface. :

I've some text field for name, description of the post etc...
and i want to use this bundle to allow the multiple upload of image for one post.

the issues are : 
- console.log($(this).val()); return something like : C:\fakepath\myimage.jpg
- var_dump(Input::file()); return an empty array

Have you got any idea ?

I'm totally lost now :/

PS : i'm working on localhost on Mac OS X (not MAMP, but functionally installation of php, mysql, and apache2)

**Comment by zimt28** [comment]
Everything should work on your local server without problems.
I actually don't know what you did there so I think I can't help you this way..
Why don't you write just one central file manager? This could simplify everything as you
don't have to edit the existing setup so much.
