### ISSUE TITLE
Making upload_dir dynamic so a website can set this different for different web pages

### ISSUE THREAD

**Issue by tester5** [zimt28/laravel-jquery-file-upload#4]
Is this possible? If so, how can I set upload_dir based on different web page requirements?

It is currently set in settings.php though these values are shared across the plugin (which am sure is the purpose).

upload_dir - '/users/folder1/files.txt' - web page 1
upload_dir - '/users/folder2/files.txt' - web page 2

any ideas on making the above possible?

**Comment by zimt28** [comment]
Sure, you don't need to use the config file. Just create an instance of the UploadHandler and pass options with your dynamic dirs.
