### ISSUE TITLE
confused how to implement in laravel (newbie)

### ISSUE THREAD

**Issue by longestdrive** [zimt28/laravel-jquery-file-upload#5]
I've installed the bundle into my laravel app and all appears there. I am however unsure how to integrate the bundle with my app. The docs focus on the plugin but I cant see much on the laravel side.

I want to use this to upload images in a 'filemanager'. From a page I have a file field that I'd like to tie this to but I'm not sure how to go about it.

I've updated my bundles.php. Do I need to make any changes to start.php?

What do I call from a controller to access the functions?

How can I test the bundle - eg is there a url I can enter on my site to call up the samples or should I start moving the bundle contents to my own controller and view files etc

Sorry - just a confused newbie

**Comment by zimt28** [comment]
Hey! For installation see here: http://bundles.laravel.com/bundle/jUpload
First I have to say that the jQuery stuff is probably not up to date as I don't work on this bundle anymore,
it's also rather a "how you could do it" than a fixed solution. If you have registered the bundle as "jupload" you should be able to call /jupload to get the sample upload screen. You do not need to update your start.php file as long as you keep thigs in the bundle.

I'd recommend you to have a look at the demo, what this bundle is about is really just the backend stuff - I think I haven't changed the original JS files at all. So you might just grab the current ones and implement the backend the way I did. Hope this helps, if you have any other questions just ask :)
